"""Agent 3: problems + solutions -> multi-page PDF."""
import re
import textwrap
from datetime import datetime

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.backends.backend_pdf import PdfPages

rcParams["font.family"] = "DejaVu Sans"
rcParams["mathtext.fontset"] = "cm"
rcParams["axes.unicode_minus"] = False

A4 = (8.27, 11.69)


def render_pdf(
    problems: list[dict],
    solutions: list[dict],
    output_path: str,
) -> None:
    sol_by_num = {str(s.get("number")): s for s in solutions}

    with PdfPages(output_path) as pdf:
        pdf.savefig(_cover_page(len(problems)))
        plt.close("all")

        for prob in problems:
            sol = sol_by_num.get(str(prob.get("number")), {})
            fig = _problem_page(prob, sol)
            pdf.savefig(fig)
            plt.close(fig)


def _cover_page(count: int):
    fig = plt.figure(figsize=A4)
    ax = fig.add_axes([0, 0, 1, 1])
    ax.axis("off")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)

    ax.text(0.5, 0.72, "Đáp án phiếu bài tập", ha="center", va="center",
            fontsize=30, fontweight="bold", color="#111827")
    ax.plot([0.25, 0.75], [0.66, 0.66], color="#2563eb", linewidth=2)
    ax.text(0.5, 0.60, f"{count} câu hỏi", ha="center", va="center",
            fontsize=18, color="#6b7280")
    ax.text(0.5, 0.52, datetime.now().strftime("%d/%m/%Y"),
            ha="center", va="center", fontsize=12, color="#9ca3af")
    ax.text(0.5, 0.05, "Generated by 3-agent Math Solver",
            ha="center", va="center", fontsize=9,
            color="#9ca3af", style="italic")
    return fig


def _problem_page(prob: dict, sol: dict):
    fig = plt.figure(figsize=A4)
    ax = fig.add_axes([0.08, 0.05, 0.84, 0.9])
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    label = prob.get("number") or "?"
    ax.text(0, 0.97, f"Bài {label}", fontsize=22, fontweight="bold",
            color="#2563eb", va="top")
    ax.plot([0, 1], [0.935, 0.935], color="#e5e7eb", linewidth=1)

    ax.text(0, 0.91, "Đề bài", fontsize=12, fontweight="bold",
            color="#374151", va="top")
    statement = prob.get("statement_text") or ""
    if not statement and prob.get("statement_math"):
        statement = f"${_sanitize_math(prob['statement_math'])}$"
    else:
        statement = _sanitize_inline(statement)
    next_y = _draw_wrapped(ax, statement, x=0, y=0.87,
                           fontsize=13, color="#111827",
                           max_chars=78, max_lines=10,
                           line_height=0.026)

    answer_y = min(next_y - 0.04, 0.55)
    ax.text(0, answer_y, "Đáp án", fontsize=12, fontweight="bold",
            color="#374151", va="top")

    ans_latex = (sol.get("answer_latex") or "").strip()
    if ans_latex and ans_latex != "?":
        ans_str = f"${_sanitize_math(ans_latex)}$"
        try:
            ax.text(0.5, answer_y - 0.06, ans_str, fontsize=22,
                    ha="center", va="top", color="#10b981")
        except Exception:
            ax.text(0.5, answer_y - 0.06, ans_latex, fontsize=18,
                    ha="center", va="top", color="#10b981")
    else:
        ax.text(0.5, answer_y - 0.06, "Không xác định",
                fontsize=16, ha="center", va="top",
                color="#dc2626", style="italic")

    if sol.get("answer_numeric"):
        ax.text(0.5, answer_y - 0.13,
                f"≈ {sol['answer_numeric']}",
                fontsize=13, ha="center", va="top", color="#6b7280")

    steps_y = answer_y - 0.22
    ax.text(0, steps_y, "Lời giải", fontsize=12, fontweight="bold",
            color="#374151", va="top")
    steps = _sanitize_inline(sol.get("steps_text") or "")
    if steps:
        _draw_wrapped(ax, steps, x=0, y=steps_y - 0.04,
                      fontsize=11, color="#374151",
                      max_chars=88, max_lines=10,
                      line_height=0.023)
    else:
        ax.text(0, steps_y - 0.04, "(không có)", fontsize=11,
                color="#9ca3af", va="top", style="italic")

    return fig


def _sanitize_math(s: str) -> str:
    s = s.strip().strip("$").strip()
    s = re.sub(r"\\text\{([^}]*)\}", r"\\mathrm{\1}", s)
    return s


def _sanitize_inline(s: str) -> str:
    return s.strip()


def _draw_wrapped(ax, text: str, x: float, y: float,
                  fontsize: int, color: str,
                  max_chars: int, max_lines: int,
                  line_height: float) -> float:
    if not text:
        return y

    placeholders: list[str] = []

    def stash(m: re.Match) -> str:
        placeholders.append(m.group(0))
        return f"\x00M{len(placeholders)-1}\x00"

    masked = re.sub(r"\$[^$\n]+\$", stash, text)

    lines: list[str] = []
    for paragraph in masked.split("\n"):
        if not paragraph.strip():
            lines.append("")
            continue
        wrapped = textwrap.wrap(paragraph, width=max_chars,
                                break_long_words=False,
                                break_on_hyphens=False)
        lines.extend(wrapped or [""])

    def restore(line: str) -> str:
        return re.sub(r"\x00M(\d+)\x00",
                      lambda m: placeholders[int(m.group(1))], line)

    for i, line in enumerate(lines[:max_lines]):
        ax.text(x, y - i * line_height, restore(line),
                fontsize=fontsize, color=color, va="top")

    return y - len(lines[:max_lines]) * line_height
