"""Agent 3: Render expression + result as a clean PDF."""
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import rcParams

rcParams["mathtext.fontset"] = "cm"
rcParams["font.family"] = "serif"


def render_pdf(
    expression: str,
    result_latex: str,
    result_numeric: str | None,
    steps: str | None,
    output_path: str,
) -> None:
    fig = plt.figure(figsize=(8.27, 11.69))
    ax = fig.add_axes([0, 0, 1, 1])
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    ax.text(
        0.5, 0.94, "Math Calculation Result",
        ha="center", va="top", fontsize=24, fontweight="bold",
        color="#111827",
    )
    ax.plot([0.1, 0.9], [0.905, 0.905], color="#2563eb", linewidth=2)

    ax.text(
        0.1, 0.83, "Original expression",
        ha="left", va="top", fontsize=13, fontweight="bold",
        color="#374151",
    )
    ax.text(
        0.5, 0.74, _wrap_math(expression),
        ha="center", va="center", fontsize=22, color="#111827",
    )

    ax.text(
        0.1, 0.60, "Result",
        ha="left", va="top", fontsize=13, fontweight="bold",
        color="#374151",
    )
    ax.text(
        0.5, 0.50, _wrap_math(result_latex),
        ha="center", va="center", fontsize=28, color="#2563eb",
    )

    if result_numeric:
        ax.text(
            0.5, 0.40, f"≈ {result_numeric}",
            ha="center", va="center", fontsize=18, color="#6b7280",
        )

    if steps:
        ax.text(
            0.1, 0.28, "Solution steps",
            ha="left", va="top", fontsize=13, fontweight="bold",
            color="#374151",
        )
        ax.text(
            0.1, 0.22, steps,
            ha="left", va="top", fontsize=11, color="#374151",
            wrap=True,
        )

    ax.text(
        0.5, 0.04, "Generated by 3-agent Math Solver",
        ha="center", va="bottom", fontsize=9, color="#9ca3af", style="italic",
    )

    fig.savefig(output_path, format="pdf", bbox_inches=None)
    plt.close(fig)


def _wrap_math(latex: str) -> str:
    s = latex.strip().strip("$").strip()
    if not s:
        return ""
    return f"${s}$"
